utilities/document/document_db.cc
utilities/document/document_db_test.cc

Summary: 
Fixed TODO. Added correct serialization
of negative integers.
Test Plan: make all check
Reviewers: igor, sdong
Reviewed By: igor
Subscribers: dhruba, leveldb
Differential Revision: https://reviews.facebook.net/D31065

Fixed negative numbers comparison in DocumentDB

---

java/Makefile
java/org/rocksdb/AbstractRocksIterator.java
java/org/rocksdb/AbstractWriteBatch.java
java/org/rocksdb/DirectSlice.java
java/org/rocksdb/RocksDB.java
java/org/rocksdb/RocksIterator.java
java/org/rocksdb/RocksIteratorInterface.java
java/org/rocksdb/WBWIRocksIterator.java
java/org/rocksdb/WriteBatch.java
java/org/rocksdb/WriteBatchInterface.java
java/org/rocksdb/WriteBatchWithIndex.java
java/org/rocksdb/test/ColumnFamilyTest.java
java/org/rocksdb/test/WriteBatchWithIndexTest.java
java/rocksjni/iterator.cc
java/rocksjni/portal.h
java/rocksjni/rocksjni.cc
java/rocksjni/write_batch.cc
java/rocksjni/write_batch_with_index.cc

This commit adds support for using WriteBatchWithIndex (and its associated WBWIIterator) from the Java API.
The Phabricator review is available here: https://reviews.facebook.net/D30891

Add WriteBatchWithIndex to the Java API

---

java/org/rocksdb/RocksDB.java
java/org/rocksdb/test/SnapshotTest.java
java/rocksjni/rocksjni.cc

With this pull request a iterator can be retrieved using a Snapshot.
This pull request depends on: https://github.com/facebook/rocksdb/pull/462
Differential: https://reviews.facebook.net/D31857

[RocksJava] Allow using ReadOptions with iterators

---

java/org/rocksdb/NativeLibraryLoader.java

Prior to this the native library loader instance didn`t
care about a state. So if library loading was called multiple
times, multiple copies of the shared object were put into
the tmp folder and loaded into the JVM.
This changed within this commit to the following behavior:
- library loading is now synchronized
- library is loaded within the first call
- if loading was successful the library loaded sets a flag
- every subsequent call checks for a boolean flag indicating if there was
already a successful attempt
Differential: https://reviews.facebook.net/D32133

[RocksJava] Fix native library loader

---

utilities/backupable/backupable_db.cc

Reduce memory footprint in backupable db.

---

java/Makefile
java/org/rocksdb/test/ColumnFamilyTest.java
java/org/rocksdb/test/DirectSliceTest.java
java/org/rocksdb/test/FlushTest.java
java/rocksjni/portal.h

Simple Java Native Objects usually are represented using
the same functionality but within different classes.
With this pull request a template class was introduced to remove
the redundant impelementation to a certain extent.
- Added a missing test to Makefile
- Added tests for some uncovered methods
Differential: https://reviews.facebook.net/D32145

[RocksJava] Cleanup portal.h & tests

---

java/rocksjni/ttl.cc

While fixing the RocksDB ColumnFamily name the TTL DB
wasn`t touched. This commit resolves this.

[RocksJava] Fix ColumnFamily name alloc in TTL DB

---

java/Makefile
java/org/rocksdb/RocksDB.java
java/org/rocksdb/TransactionLogIterator.java
java/org/rocksdb/WriteBatch.java
java/org/rocksdb/test/RocksDBTest.java
java/org/rocksdb/test/TransactionLogIteratorTest.java
java/rocksjni/rocksjni.cc
java/rocksjni/transaction_log.cc

This pull request exposes further C++ methods to the Java-API
* GetUpdatesSince
* GetLatestSequenceNumber
* EnableFileDeletions
* DisableFileDeletions
This pull requests depends on: https://github.com/facebook/rocksdb/pull/472
Differential: https://reviews.facebook.net/D32151

[RocksJava] GetUpdatesSince

---

java/org/rocksdb/DBOptions.java
java/org/rocksdb/DBOptionsInterface.java
java/org/rocksdb/Options.java

- see: 62ad0a9b19f0be4cefa70b6b32876e764b7f3c11

[RocksJava] Deprecate setSkipLogErrorOnRecovery

---

util/env_posix.cc

It doesn't seem this is needed.

remove old debugging message (#487)

---

db/c.cc
db/c_test.c
examples/c_simple_example.c
include/rocksdb/c.h

Added simple wrappings allowing backing up RocksDB in C.
I don't have a lot of experience in C++, so comments are welcome.

Allow creating and restoring backups from C

---

java/src/main/java/org/rocksdb/FlushOptions.java

`SetWaitForFlush` did not set `WaitForFlush` properly.

[RocksJava] FlushOptions Correction

---

java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/MergeOperator.java
java/src/main/java/org/rocksdb/RocksIteratorInterface.java
java/src/main/java/org/rocksdb/WriteBatchInterface.java

Removed redundant access modifier in interfaces.

[RocksJava] Redundant access-modifier in interfaces

---

java/src/main/java/org/rocksdb/AbstractComparator.java
java/src/main/java/org/rocksdb/AbstractSlice.java
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/main/java/org/rocksdb/WriteBatchWithIndex.java

Resolved raw use of parametrized class issues.

[RocksJava] Raw use of parametrized class

---

java/Makefile
java/src/test/java/org/rocksdb/NativeLibraryLoaderTest.java
java/src/test/java/org/rocksdb/util/EnvironmentTest.java

- NativeLibraryLoader Test
- EnvironmentTest Bugfix

[RocksJava] RocksJava Testcases

---

java/Makefile
java/src/main/java/org/rocksdb/NativeLibraryLoader.java
java/src/test/java/org/rocksdb/NativeLibraryLoaderTest.java

- Resolve problem while using a temporary data folder
- Fix test

[RocksJava] Fix NativeLibraryLoader

---

java/rocksjni.pom

With the last folder layout change a bug was introduced which
prevents Jacoco from working correctly.

[RocksJava] Fix broken jacoco report

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/ColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Summary: Added optimize_filters_for_hits option.
Test Plan:
make clean jclean rocksdbjava jtest
mvn -f rocksjni.pom package
Reviewers: adamretter, yhchiang, ankgup87
Differential Revision: https://reviews.facebook.net/D35013

[RocksJava] OptimizeFiltersForHits

---

java/src/main/java/org/rocksdb/Logger.java

Added information about performance penalties using a custom
logger implementation.

[RocksJava] Enhanced Logger comment

---

java/samples/src/main/java/RocksDBSample.java

One of the latest commits broke the sample code. This
resolves the introduced bug.

[RocksJava] Java sample bugfix

---

java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java

Added missing JavaDoc annotations to resolve two warnings.

[RocksJava] Add missing JavaDoc annotations

---

java/rocksjni.pom

The maven build had failing tests previous to this commit.

[RocksJava] Maven build fix

---

java/src/test/java/org/rocksdb/DBOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Fixed two tests which hit an assertion in 3.10.

[RocksJava] Fix RateLimiter Tests in 3.10

---

dockerbuild.sh
tools/Dockerfile
tools/dockerbuild.sh

currently on DockerHub at https://registry.hub.docker.com/u/arschles/rocksdb-ldb/

adding docker build script and dockerfile for tools

---

db/c.cc
include/rocksdb/c.h
util/thread_operation.h

also fixed an import that had been bugging me ;)

C: add more block based table stuff, some aux slice transform/merge ops

---

db/write_batch.cc
db/write_batch_base.cc
db/write_batch_internal.h
include/rocksdb/write_batch.h
include/rocksdb/write_batch_base.h

also hooked up WriteBatchInternal
not sure if there were some caveats I'm not aware of in hooking this up, it just seemed missing.

WriteBatch.Merge w/ SliceParts support

---

db/c.cc
db/c_test.c
include/rocksdb/c.h

sidenote: naming convention was most challenging part: since C api doesn't say anything about 'Slice' or 'SliceParts' I went for the 'writev' convention. totally open to ideas though

C: add support for WriteBatch SliceParts params

---

INSTALL.md

Updated OS X instructions, replace homebrew/dupes with homebrew/versions

---

db/c.cc
include/rocksdb/c.h

C-wrapper for ascii statistics

C api: human-readable statistics

---

CMakeLists.txt
port/win/port_win.cc
port/win/port_win.h

Missing and duplicate files in CMake
Missing definition of port::Crash

Fix windows build after refactoring

---

util/thread_local.cc

Commit 257ee89 added a static destruction helper to avoid notional
"leaks" of TLS on main thread exit. This helper fails to compile on
OS X (and presumably Windows, though I haven't checked), which lacks
the __thread storage class StaticMeta::tls_ member.
This patch fixes the builds. Do note that the static cleanup mechanism
may be somewhat brittle and atexit(3) may be a more suitable approach
to releasing the main thread's TLS if it's highly desirable for this
memory to not be reported "reachable" by Valgrind at exit.
I've signed the CLA.

Fix OSX + Windows build

---

.travis.yml

Creating pull request to trigger travis build.

Upgrade travis to new architecture

---

java/src/test/java/org/rocksdb/test/RocksJunitRunner.java

Closes https://github.com/facebook/rocksdb/issues/724

Exit with non-zero status if one or more Java tests fail

---

db/dbformat.h
include/rocksdb/write_batch.h
util/env_posix.cc

These are really micro optimizations, small and not at all important. Just what immediately jumped at me when looking through the code.

Micro optimizations

---

include/rocksdb/utilities/backupable_db.h

otherwise Visual Studio will have trouble compiling this file

add missing header required for std::function

---

util/arena.cc

The previous memory allocation procedures tried to allocate memory
via `new` or `mmap` and inserted the pointer to the memory into an
std::vector afterwards. In case `new` or `mmap` threw or returned
a nullptr, no memory was leaking. If `new` or `mmap` worked ok, the
following `vector::push_back` could still fail and throw an exception.
In this case, the memory just allocated was leaked.
The fix is to reserve space in the target memory pointer vector
beforehand. If this throws, then no memory is allocated nor leaked.
If the reserve works but the actual allocation fails, still no
memory is leaked, only the target vector will have space for at
least one more element than actually required (but this may be
reused for the next allocation)

prevent potential memleaks in Arena::Allocate*()

---

build_tools/run_ci_db_test.ps1

Introduce proper command line arguments so we can control the script
Add appveyor support
Add an ability to run all other (non db_tests) test executables in parallel
Use .NET HashSet instead of empty valued hashtable to improve the looks
TODO: Some of the tests do not use GTests and need to improve log parsing

Improve test running scripts

---

CMakeLists.txt

Add shared_linked `DEBUG` flag, remove port from among the include directories.

FIx up build options

---

include/rocksdb/convenience.h
table/plain_table_factory.cc
table/plain_table_factory.h
util/options_helper.cc
util/options_helper.h
util/options_test.cc

See https://github.com/facebook/rocksdb/issues/793 
- Added GetPlainTableOptionsFromMap() for string option parser
- Added corresponding test for GetPlainTableOptionsFromMap()

Support PlainTableOption in option_helper.cc

---

CMakeLists.txt
db/db_test.cc

The code compiles cleanly for the most part. Fix db_test.
Move debug file to testutil library.

Do not suppress C4018 'expression' : signed/unsigned mismatch

---

utilities/geodb/geodb_test.cc

Hi @satnam6502, appveyor CI build start to failed after this change: 
https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.75 
I believe it's related to the "Add RocksDb/GeoDb Iterator interface" commit. 
This commit fix the problem. 
Could you please merge this commit? Thanks.

Fix appveyor build failure

---

build_tools/run_ci_db_test.ps1

PowerShell seems to have a hard time when a flood of async tasks is
scheduled at the same time.
WaitForMultipleObjects() in Windows can only take up
to 64 process handles and if you want to handle more than you should write
some additional code which can be sub-optimal. I.e to implement Wait-Job -Any.
Introduced a $Concurrency parameter with a default value of 62.
So in the new version the script fires up up to $Concurrency value
and wait for anything to complete before starting any more processes.
This improved matters greatly. Individual tests against ramdrive now
run in 8 minutes and all of the 200+ db_tests run in 9 minutes with concurrency
values of 8-16. About 48 is required to load a CPU on my box running against HD
but that does not improve running times much.
Other changes …

Improve concurrency when running tests

---

table/block_based_table_factory.cc
table/block_based_table_factory.h
table/plain_table_factory.cc
table/plain_table_factory.h
util/options_helper.cc
util/options_helper.h
util/options_parser.cc
util/options_test.cc

Follow up on https://github.com/facebook/rocksdb/pull/797
@siying, as we have discussed, here's the fix.

Option Helper Refactoring

---

include/rocksdb/convenience.h
util/options_helper.cc
util/options_test.cc

New pull request for https://github.com/facebook/rocksdb/pull/817.
Hi @IslamAbdelRahman, as requested, rebased and resolved the conflicts. 
Thank you.

Support Memtable Factory Parse in option_helper.cc

---

build_tools/run_ci_db_test.ps1

Previous check in broke test second attempt

Fix log names when scheduling runs and reruns

---

CMakeLists.txt
db/db_test.cc
port/win/port_win.cc
port/win/port_win.h
util/thread_local_test.cc

This resolves https://github.com/facebook/rocksdb/issues/809

Build on Visual Studio 2015 Update 1

---

CMakeLists.txt
port/win/port_win.h
tools/db_stress.cc

Fix warnings
Take advantage of native snprintf on VS 15

Fix up VS 15 build.

---

db/db_bench.cc

In benchmarks that mix multiple types of operations, such as readrandomwriterandom and seekrandomwhilemerging, we wish to have separate histogram measurements for latency.
This change split the histogram to per OperationType: 
std::unordered_map<OperationType, HistogramImpl> hist_

Split histogram per OperationType in db_bench

---

db/version_builder.cc
db/version_set.cc
db/version_set.h

See https://github.com/facebook/rocksdb/issues/813

Fix EstimateNumKeys Counter Inaccurate Issue

---

HISTORY.md
build_tools/run_ci_db_test.ps1
db/compaction_job.h
db/db_test.cc
db/file_indexer.h
db/write_controller.cc
hdfs/README
include/rocksdb/listener.h
include/rocksdb/options.h
include/rocksdb/table.h
include/rocksdb/utilities/transaction.h
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
port/port_posix.h
tools/auto_sanity_test.sh
tools/rdb/API.md
util/sync_point.h
util/thread_local.h
utilities/write_batch_with_index/write_batch_with_index.cc

fix typos in comments

---

db/compaction_job.cc

Here it is unnecessary to use `std::set`. We can just construct a `std::vector` containing all boundaries, and then sort it. `std::set` uses balanced tree as internal implementation, which has more overhead than sorting.

Sorting std::vector instead of using std::set

---

CMakeLists.txt
db/compaction.cc
db/compaction_job.cc
db/compaction_job_stats_test.cc
db/corruption_test.cc
db/db_bench.cc
db/db_impl.cc
db/db_test.cc
db/event_helpers.cc
db/internal_stats.cc
db/version_edit.h
db/version_set.cc
include/rocksdb/delete_scheduler.h
memtable/hash_cuckoo_rep.cc
port/win/env_win.cc
port/win/port_win.cc
table/cuckoo_table_builder.cc
table/cuckoo_table_builder_test.cc
table/cuckoo_table_reader_test.cc
table/plain_table_index.cc
third-party/fbson/FbsonJsonParser.h
tools/db_stress.cc
tools/ldb_cmd.h
tools/write_stress.cc
util/arena_test.cc
util/histogram.cc
util/rate_limiter.h
utilities/geodb/geodb_impl.cc
utilities/spatialdb/utils.h

Mostly due to the fact that there are differences in sizes of int,long
on 64 bit systems vs GNU.

Enable MS compiler warning c4244.

---

hdfs/env_hdfs.h

@siying 
This fixes the build failure of hdfs environment.

fix vfunc inconsistency between env_hdfs and env

---

USERS.md

We started using RocksDB for our high performance counters services, and it worked so well that we've started migrating as much as we can off of Riak and Redis and into custom RocksDB-based services.

Add Smyte to USERS.md

---

port/port_posix.h
port/win/port_win.h
util/statistics.h

Use Yield macro to make it a little more portable between platforms.

Align statistics

---

.travis.yml
Makefile
db/db_compaction_test.cc
db/db_impl.cc
db/db_test.cc
java/src/main/java/org/rocksdb/util/Environment.java
util/options_builder.cc
utilities/geodb/geodb_impl.cc

Minor changes to rocksdb to allow it to build on solaris with gcc49.

Solaris Build

---

USERS.md

VWO, the flagship product of Wingify, uses RocksDB to populate the list of URLs where clients can run A/B test campaigns. It is also used to provide a way for the clients to see if VWO's Smart Code is installed on a specific URL of their account.

Add Wingify to USERS.md

---

Makefile

fix build for raspberry 2

---

CMakeLists.txt
java/CMakeLists.txt
java/rocksjni/backupablejni.cc
java/rocksjni/backupenginejni.cc
java/rocksjni/options.cc
java/rocksjni/portal.h
java/rocksjni/restorejni.cc
java/rocksjni/rocksjni.cc
java/rocksjni/statistics.cc
java/rocksjni/write_batch_test.cc
java/src/main/java/org/rocksdb/NativeLibraryLoader.java
java/src/main/java/org/rocksdb/util/Environment.java
java/src/test/java/org/rocksdb/BackupableDBOptionsTest.java
java/src/test/java/org/rocksdb/InfoLogLevelTest.java
java/src/test/java/org/rocksdb/NativeLibraryLoaderTest.java
java/src/test/java/org/rocksdb/util/EnvironmentTest.java

Initial support for building JNI library for Windows. Also some modification in Java unit tests to make it pass.
@yuslepukhin I was modifying CMakeLists.txt to add support for Windows JNI build. Can you check if changes are OK?
#703

Adding support for Windows JNI build

---

java/Makefile
java/src/test/java/org/rocksdb/WriteBatchThreadedTest.java

Influenced by https://github.com/facebook/rocksdb/issues/971

Threaded tests for WriteBatch

---

util/options.cc

Small typo in the options logging.

fixes typo in options logging

---

db/auto_roll_logger.h
util/thread_local_test.cc

https://github.com/facebook/rocksdb/issues/1002

This addresses build issues on Windows

---

port/win/env_win.cc

by using default implementation for now as it works.

Implement ConsistentChildrenAttribute on Windows

---

USERS.md

As requested, we added ourselves to the USERS.md file.

Added quasardb to the USERS.md file

---

CMakeLists.txt
tools/db_bench_tool.cc
util/transaction_test_util.h
utilities/transactions/optimistic_transaction_test.cc
utilities/transactions/transaction_test.cc

Fixed the error in 
https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.755

Fix AppVeyor build error

---

db/managed_iterator.cc
db/memtable_list.cc
db/version_set.cc
table/block_based_table_factory.cc
util/arena.cc
util/random.h
util/testutil.cc

These are mainly minor fixes/warning issues. Note that it fixes potential issues on 32-bit platforms.

Fixes warnings and ensure correct int behavior on 32-bit platforms.

---

db/db_impl.cc
db/db_test2.cc
include/rocksdb/wal_filter.h

Avoid overloaded virtual function

---

port/win/env_win.cc

Using async file handle and wrapping sync operations on top of async seems to provide better parallelism on Windows.

Use async file handle for better parallelism

---

arcanist_util/cpp_linter/cpplint.py
db/compaction.h
db/db_impl.h
db/db_iterator_test.cc
db/db_test.cc
include/rocksdb/convenience.h
include/rocksdb/options.h
include/rocksdb/utilities/transaction.h
include/rocksdb/utilities/transaction_db.h
port/win/env_win.cc
table/block_based_table_reader.h
utilities/transactions/transaction_base.h
utilities/transactions/transaction_lock_mgr.cc

Signed-off-by: Li Peng <lip@dtdream.com>

fix typos and remove duplicated words

---

port/win/env_win.cc

make preallocation inline with other writable files
make sure that we map no more than pre-allocated size.

Fix multiple issues with WinMmapFile fo sequential writing

---

java/rocksjni/rocksjni.cc
java/src/main/java/org/rocksdb/RocksDB.java
java/src/test/java/org/rocksdb/RocksDBTest.java

Closes https://github.com/facebook/rocksdb/issues/1071

Add support for PauseBackgroundWork and ContinueBackgroundWork to the Java API

---

CMakeLists.txt
port/win/env_win.cc

Implement GetUniqueIdFromFile to support new tests and the feature.

Fix build issue.

---

appveyor.yml

Disable long running GroupCommitTest

---

db/c.cc
include/rocksdb/c.h

Expose report_bg_io_stats option in the C API.

---

utilities/checkpoint/checkpoint.cc

The file path "full_private_path + subchild" is not correct, should have "/" in the middle.

fix delete file bug when do checkpoint

---

java/rocksjni/statistics.cc
java/src/main/java/org/rocksdb/Statistics.java
java/src/main/java/org/rocksdb/StatisticsCollector.java

Closes https://github.com/facebook/rocksdb/issues/835

Java API - Rename geHistogramData -> getHistogramData

---

db/db_impl.h
db/db_wal_test.cc
db/write_batch.cc
db/write_thread.h
include/rocksdb/statistics.h
third-party/fbson/FbsonJsonParser.h
utilities/persistent_cache/hash_table.h
utilities/persistent_cache/lrulist.h

just fix simple typos error on comments.

fix simple typos

---

util/string_util.h

Submitted-by: Willem Jan Withagen <wjw@digiware.nl>

FreeBSD does not have std::to_string (v2)

---

CMakeLists.txt
tools/db_bench_tool.cc

Some files were not included in CMakeLists.txt.
Fixed default perf level in db_bench_tool.cc

Fixed Minor Bug on Windows Build and db_bench_tool.cc

---

build_tools/build_detect_platform

There's an errata in include numaif.h file.

fix errata in libnuma test

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/ReadOptions.java
java/src/main/java/org/rocksdb/ReadTier.java
java/src/test/java/org/rocksdb/ReadOptionsTest.java

Closes https://github.com/facebook/rocksdb/issues/932

Added missing Java ReadOptions settings

---

CMakeLists.txt
utilities/col_buf_decoder.cc
utilities/column_aware_encoding_exp.cc
utilities/column_aware_encoding_util.cc
utilities/persistent_cache/block_cache_tier.h
utilities/persistent_cache/block_cache_tier_file.cc
utilities/persistent_cache/block_cache_tier_file.h
utilities/persistent_cache/persistent_cache_test.cc
utilities/persistent_cache/persistent_cache_tier.h

Note. port headers exist for abstracting platform differences not bringing them up by including platform specific headers.

Fix Windows build issues

---

java/Makefile
java/rocksjni/options.cc
java/rocksjni/rocksjni.cc
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/MutableColumnFamilyOptions.java
java/src/main/java/org/rocksdb/MutableColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/main/java/org/rocksdb/RocksDB.java
java/src/test/java/org/rocksdb/ColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/MutableColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java
java/src/test/java/org/rocksdb/RocksDBTest.java

Implemented `RocksDB#setOptions` and associated mutable/immutable options

Added SetOptions support to RocksJava

---

db/db_impl.h
db/db_impl_add_file.cc
db/db_sst_test.cc
db/db_test.cc
include/rocksdb/db.h
include/rocksdb/utilities/stackable_db.h

This PR contain the changes that to add check_snapshot in DB's AddFile function
issue: #1249

Added check_snapshot option in the DB's AddFile function

---

arcanist_util/__phutil_library_map__.php
arcanist_util/config/RocksDBCommonHelper.php
arcanist_util/unit_engine/FacebookOldFbcodeUnitTestEngine.php

https://reviews.facebook.net/D61911
https://reviews.facebook.net/D61917

Fixes for arcanist config

---

db/c.cc
include/rocksdb/c.h
include/rocksdb/compaction_filter.h

c abi: allow compaction filter ignore snapshot

---

java/rocksjni/rocksjni.cc
java/src/main/java/org/rocksdb/Experimental.java
java/src/main/java/org/rocksdb/RocksDB.java
java/src/test/java/org/rocksdb/RocksDBTest.java

Added `RocksDB#singleDelete` and renamed/deprecated `RocksDB#remove` -> `RocksDB#delete`

Add singleDelete to RocksJava

---

java/rocksjni/options.cc

Small issue with allocation; Similar to https://github.com/facebook/rocksdb/issues/1220

Fix the Windows build of RocksDB Java. 

---

include/rocksdb/c.h

Remove extraneous function prototypes from c.h

---

db/c.cc
db/c_test.c
include/rocksdb/c.h

add C api for set wal_recovery_mode

add C api for set wal_recovery_mode

---

hdfs/env_hdfs.h
java/rocksjni/options.cc
java/src/main/java/org/rocksdb/DBOptions.java

Fix bug in UnSchedule() function requested a return-value and add function to set and get the delay_write_rate option

Fix HdfsEnv::UnSchedule() API error

---

java/src/main/java/org/rocksdb/RocksDB.java

Similar to: https://github.com/facebook/rocksdb/pull/1344

Use size hint for HashMap in multiGet

---

util/log_write_bench.cc

Hello and thanks for RocksDB,
When log_write_bench is run with the `-bytes_per_sync` option, the option does not influence any \*sync\* behaviour.
```
> strace -e trace=write,sync_file_range ./log_write_bench -record_interval 0 -record_size 1048576 -num_records 11 -bytes_per_sync 2097152 2>&1 | egrep '^(sync|write.*XXXX)'
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576
write(3, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"..., 1048576) = 1048576 …
```

Fix log_write_bench -bytes_per_sync option.

---

table/scoped_arena_iterator.h

This brings down write_batch_test immediately.
Due to the fact that memory does not go away the code continues to operate on a destroyed internal iterator.

Fix scoped arena iterator

---

CMakeLists.txt

Closes https://github.com/facebook/rocksdb/issues/1377

[doc] Document that Visual Studio 2015+ is now required for Windows

---

java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/MutableColumnFamilyOptionsInterface.java

Travis Java build is failing. Try to fix it.

Fix @see in two Java functions

---

HISTORY.md
include/rocksdb/version.h

Summary:
Bump RocksDB version to 4.13
Test Plan:
RocksDB unit tests
Reviewers: sdong, IslamAbdelRahman, andrewkr, lightmark
Subscribers: leveldb

Bump RocksDB version to 4.13

---

HISTORY.md
db/memtable.cc
db/merge_context.h
include/rocksdb/merge_operator.h
table/get_context.cc

@sagar0 Could you PTAL? Thanks!

[Not for merging] Cherrypicks into 5.15.fb

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/DBOptions.java
java/src/main/java/org/rocksdb/Env.java
java/src/main/java/org/rocksdb/MutableDBOptions.java
java/src/main/java/org/rocksdb/MutableDBOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/DBOptionsTest.java
java/src/test/java/org/rocksdb/MutableDBOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Looking to pick #6167 (crash fix) and #6152 (Java options to work around crash in #6127)

[ci validation for manual backport] 6.6.fb java backports

---

HISTORY.md
db/compaction/compaction_job.cc
db/corruption_test.cc
db/db_basic_test.cc
db/db_impl/db_impl.cc
db/db_impl/db_impl.h
db/db_impl/db_impl_open.cc
db/db_impl/db_impl_readonly.cc
db/db_table_properties_test.cc
db/db_test_util.cc
db/db_test_util.h
db/external_sst_file_ingestion_job.cc
file/file_util.cc
file/file_util.h
include/rocksdb/db.h
include/rocksdb/utilities/stackable_db.h
include/rocksdb/version.h

Will not land. All commits come from the following landed/approved PRs.
#7586, #7578, #7627, #7636 and one last commit (taken from #7521).
The last commit is an one-liner from
```
env_->GetCurrentTime(&unix_time);  // Ignore error
```
to
```
env_->GetCurrentTime(&unix_time).PermitUncheckedError();  // Ignore error
```
so that corruption_test compiled with `ASSERT_STATUS_CHECKED=1` can pass.
Once tests pass, will push to upstream 6.14.fb branch.

[NO LAND][TEST] Patch release 6.14.4

---

HISTORY.md

try the push

---

HISTORY.md
db/db_basic_test.cc
db/db_impl/db_impl_files.cc

Summary: A low-touch verison of
https://github.com/facebook/rocksdb/pull/10173
Test Plan: updated unit test

[CI ONLY] Patch version of empty IDENTITY file fix

---

HISTORY.md
db/db_basic_test.cc
db/db_impl/db_impl.cc
include/rocksdb/options.h
include/rocksdb/version.h
tools/db_bench_tool.cc

As title.
Test plan
- make check
- CI

Release RocksDB 7.4.3

---

HISTORY.md
db/db_basic_test.cc
db/db_filesnapshot.cc
db/db_impl/db_impl.cc
db/db_impl/db_impl.h
db/db_impl/db_impl_compaction_flush.cc
db/db_impl/db_impl_files.cc
db/db_impl/db_impl_write.cc
db/db_wal_test.cc
db/db_write_test.cc
file/writable_file_writer.cc
file/writable_file_writer.h
include/rocksdb/options.h
include/rocksdb/version.h
tools/db_bench_tool.cc
utilities/checkpoint/checkpoint_test.cc

Release RocksDB 7.3.2

---

HISTORY.md
include/rocksdb/version.h
table/compaction_merging_iterator.cc
table/merging_iterator.cc

Cherry-picked https://github.com/facebook/rocksdb/pull/11782 and updated changelog and version.

8.5.1 bug fix

---

HISTORY.md
db/column_family.cc
db/db_compaction_test.cc
db/db_impl/db_impl.cc
db/db_impl/db_impl.h
db/periodic_task_scheduler.cc
db/periodic_task_scheduler.h
db/periodic_task_scheduler_test.cc
include/rocksdb/version.h
unreleased_history/behavior_changes/periodic-compaction-trigger.md
utilities/backup/backup_engine.cc

Summary: added a new release note for the bug fix in backup engine that will need to be backported to main.
Test plan: CI

10.4.1 Patch Release

---

HISTORY.md
db/version_set.cc
db_stress_tool/db_stress_test_base.cc
include/rocksdb/version.h
table/block_based/block_based_table_iterator.cc
table/block_based/user_defined_index_wrapper.h
table/table_test.cc
unreleased_history/bug_fixes/udi_empty_scan_range_fix.md

10.6.3 release
