facebook/rocksdb

examples/c_simple_example.c

Valgrind report prior to this fix:
==20829== Memcheck, a memory error detector
==20829== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==20829== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==20829== Command: ./c_simple_example
==20829==
==20829== Invalid read of size 1
==20829==    at 0x4C2F1C8: strcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20829==    by 0x422522: main (in /home/user/rocksgit/transfer/rocksdb-git/examples/c_simple_example)
==20829==  Address 0x5f60df5 is 0 bytes after a block of size 5 alloc'd
==20829==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20829==    by 0x4226D5: CopyString (c.cc:498)
==20829==    by 0x423032: rocksdb_get (c.cc:730)
==20829==    by 0x4224EB: main …

Memory issue fix in c_simple_example

---

java/RocksDBColumnFamilySample.java
java/org/rocksdb/ColumnFamilyDescriptor.java
java/org/rocksdb/RocksDB.java
java/org/rocksdb/test/AbstractComparatorTest.java
java/org/rocksdb/test/ColumnFamilyTest.java
java/org/rocksdb/test/KeyMayExistTest.java
java/org/rocksdb/test/MergeTest.java
java/org/rocksdb/test/ReadOnlyTest.java
java/org/rocksdb/test/RocksDBTest.java
java/rocksjni/portal.h
java/rocksjni/rocksjni.cc

Previous to this commit ColumnFamilyDescriptor took a String as name for the ColumnFamily name. String is however encoding dependent which is bad because listColumnFamilies returns byte arrays without any encoding information.
All public API calls were deprecated and flagged to be removed in 3.10.0
Differential: https://reviews.facebook.net/D30525
Solves issue: https://github.com/facebook/rocksdb/pull/441

[RocksJava] ColumnFamilyDescriptor alignment with listColumnFamilies

---

util/thread_local.cc

I got a build failure on linux with clang 3.5:
/usr/local/bin/clang++   -DCLANG_INCLUDEPATH=/usr/local/lib/clang/3.5.0/include/ -DOS_Linux -DRCT_DB_USE_ROCKSDB -DRCT_HAVE_ZLIB -DROCKSDB_PLATFORM_POSIX -DRTAGS_BIN=\"/home/jhanssen/dev/rtags/bin/\" -Wextra -Wall -Wall -fstack-protector-all -Wstack-protector -std=c++0x -fpic -stdlib=libc++ -std=c++0x -fpic -stdlib=libc++ -O3 -DNDEBUG -I/usr/local/include -isystem src/rct/3rdparty/rocksdb -isystem src/rct/3rdparty/rocksdb/include -Isrc/rct -Isrc/include/rct -Isrc/include/rct/.. -Isrc -Isrc/rct/include -Isrc/rct/include/rct    -fcolor-diagnostics -Wall -MMD -MT src/CMakeFiles/rct.dir/rct/3rdparty/rocksdb/util/thread_local.cc.o -MF "src/CMakeFiles/rct.dir/rct/3rdparty/rocksdb/util/thread_local.cc.o.d" -o …

Build with clang 3.5 on Linux.

---

include/rocksdb/c.h

@igorcanadi 
Remove duplicated declarations in C header.

Remove duplicated method declarations in C header.

---

java/org/rocksdb/AbstractRocksIterator.java
java/org/rocksdb/RocksIteratorInterface.java
java/org/rocksdb/test/WriteBatchWithIndexTest.java

This pull request includes two commits:
- Java8 JavaDoc corrections. Some illegal tags were used which broke JavaDoc generation.
- WriteBatchWithIndex was using incorrect assert statements. These statements make use now as inteded equals method for comparison.

[RocksJava] Fixes to latest WriteBatchWithIndex addition

---

java/rocksjni/slice.cc

DirectSlice fix for non terminated String copy. This lead sometimes
to problems with DirectSliceTest.

[RocksJava] DirectSlice String termination fix

---

java/Makefile
java/org/rocksdb/TtlDB.java
java/org/rocksdb/test/TtlDBTest.java
java/rocksjni/ttl.cc

Added TTL DB support to RocksJava. It is now possible to use the RocksDB time to live feature in Java.
Differential: https://reviews.facebook.net/D31449

[RocksJava] TTL DB support

---

java/rocksjni/rocksjni.cc

Previous to this commit there was a problem with unterminated
String usage as jByteArrays are not zero terminated.
Differential: https://reviews.facebook.net/D31809

[RocksJava] ColumnFamily name JNI correction

---

java/org/rocksdb/BlockBasedTableConfig.java
java/org/rocksdb/test/BlockBasedTableConfigTest.java
java/rocksjni/table.cc

- Added  support for format version in BlockBasedTableFormatConfig
This depends on: https://github.com/facebook/rocksdb/pull/464

[RocksJava] Format version support in BlockBasedTableConfig

---

java/Makefile
java/org/rocksdb/Snapshot.java
java/org/rocksdb/test/SnapshotTest.java
java/rocksjni/rocksjni.cc
java/rocksjni/snapshot.cc

Summary:
As the C++ part exposes now SequenceNumber retrieval
for Snapshots we want this obviously also in the Java API.
Differential: https://reviews.facebook.net/D32571

[RocksJava] Snapshot - GetSequenceNumber

---

java/RELEASE.md

The version change instruction is obsolete with the change
that maven pulls versioning information from version.h.
@adamretter can you look into this.
See as reference: https://github.com/facebook/rocksdb/commit/b8d5e3f08e075fb37af73fdd9dceb7d369f38dd7

Release.md - Remove version change instruction

---

HISTORY.md
db/compaction_picker_test.cc
db/table_properties_collector_test.cc
include/rocksdb/env.h
util/auto_roll_logger.h
util/env_test.cc
util/mock_env.cc
util/options_test.cc
util/posix_logger.h

I would like to alter `void Logv(const InfoLogLevel log_level, const char* format, va_list ap)` to virtual. That`s because i would like to add a Logger for RocksJava. 
Logging from a higher level API would require to know about the log level which is not easily accessible from `virtual void Logv(const char* format, va_list ap)`. It would also offer the possibility to override the loglevel from API, what`s not possible if this method remains as is.
@igorcanadi can you look into this please?  
I checked the build using `make all` and everything compiles.

Switch logv with loglevel to virtual

---

java/rocksjni/rocksjni.cc
java/rocksjni/ttl.cc
java/src/test/java/org/rocksdb/ColumnFamilyTest.java

Bytes are currently misinterpreted by RocksJava if the byte array contains zero bytes within its content. For Strings it is usually not useful that zero bytes are present but every kind of byte array values are allowed. It might be the case that zero padding or other kinds of byte values are applied.
- Removed additional string copy
- Added 3 new tests
@xpromache there you are.
Differential: https://reviews.facebook.net/D33165

[RocksJava] CF Name shall handle bytes correctly

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/ColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Summary: Added LevelCompactionDynamicLevelBytes to Options.
Test Plan:
make clean jclean rocksdbjava jtest
mvn -f rocksjni.pom package
Reviewers: adamretter, ankgup87, yhchiang
Differential Revision: https://reviews.facebook.net/D34857

[RocksJava] Added LevelCompactionDynamicLevelBytes to Options

---

java/rocksjni/memtablejni.cc
java/rocksjni/options.cc
java/rocksjni/portal.h
java/samples/src/main/java/RocksDBSample.java
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/DBOptions.java
java/src/main/java/org/rocksdb/DBOptionsInterface.java
java/src/main/java/org/rocksdb/HashLinkedListMemTableConfig.java
java/src/main/java/org/rocksdb/HashSkipListMemTableConfig.java
java/src/main/java/org/rocksdb/MemTableConfig.java
java/src/main/java/org/rocksdb/Options.java
java/src/main/java/org/rocksdb/SkipListMemTableConfig.java
java/src/main/java/org/rocksdb/VectorMemTableConfig.java

Summary:
Before this change: overflowing size_t values led to a checked Exception.
After that change:
size_t overflows on 32-Bit architecture, throw now an IllegalArgumentException,
which removes the necessity for a developer to catch these Exceptions explicitly.
This is especially an advantage for developers targeting 64-Bit systems because
it is not necessary anymore to catch exceptions which are never thrown on a 64-Bit
system.
Test Plan:
make clean jclean rocksdbjava jtest
mvn -f rocksjni.pom package
Reviewers: adamretter, yhchiang, ankgup87
Differential Revision: https://reviews.facebook.net/D34923

[RocksJava] 32-Bit adjustments

---

java/rocksjni/options.cc
java/rocksjni/portal.h
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/CompressionType.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/ColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Summary:
RocksDB offers the possibility to set different compression types
on a per level basis. This shall be also available using RocksJava.
Test Plan:
make rocksdbjava
make jtest
Reviewers: adamretter, yhchiang, ankgup87
Differential Revision: https://reviews.facebook.net/D35577

[RocksJava] Add compression per level to API

---

java/Makefile
java/benchmark/src/main/java/org/rocksdb/benchmark/DbBenchmark.java
java/rocksjni/env.cc
java/src/main/java/org/rocksdb/Env.java
java/src/main/java/org/rocksdb/Options.java
java/src/main/java/org/rocksdb/RocksEnv.java
java/src/main/java/org/rocksdb/RocksMemEnv.java
java/src/test/java/org/rocksdb/OptionsTest.java
java/src/test/java/org/rocksdb/RocksEnvTest.java
java/src/test/java/org/rocksdb/RocksMemEnvTest.java

Summary:
In 3.10 the C++ code was extended with a MemEnv implementation. This
is now also available in RocksJava.
Changes:
- Extraced abstract super class Env
- Introduced RocksMemEnv
- Remove unnecessary disposeInternal method. The disposal of the default environment is managed by C++ so there needs to be no disposeInternal method in Java.
- Introduced a RocksMemEnvTest, which is aligned with the C++ equivalent.
Test Plan:
make rocksdbjava
make jtest
Reviewers: adamretter, yhchiang, ankgup87
Differential Revision: https://reviews.facebook.net/D35619

[RocksJava] Expose MemEnv in RocksJava

---

Makefile

Usage:
make clean rocksdbjavastatic
Dependency:
LZ4
To install LZ4:
git clone https://github.com/Cyan4973/lz4.git && \
cd lz4/lib && \
make install
Alternativel installation method:
curl -O https://codeload.github.com/Cyan4973/lz4/tar.gz/r127
mv r127 lz4-r127.tar.gz
tar xvzf lz4-r127.tar.gz
cd lz4-r127/lib && \
make install
Signed-off-by: Pooya Shareghi <shareghi@gmail.com>

[RocksJava] Added static lz4 support for roccksjavastatic

---

db/db_bench.cc

When compiling on RH5 with g++4.7.4 I have got an error:
[maa@srv2-nskb-devg2 rocksdb-master]$ CXX=/usr/local/CC/gcc-4.7.4/bin/g++ EXTRA_CXXFLAGS=-std=c++11 DISABLE_WARNING_AS_ERROR=1  make db_bench
CC       db/db_bench.o
db/db_bench.cc: In member function 'rocksdb::Slice rocksdb::Benchmark::AllocateKey(std::unique_ptr<const char []>*)':
db/db_bench.cc:1434:41: error: use of deleted function 'void std::unique_ptr<_Tp [], _Dp>::reset(_Up) [with _Up = char*; _Tp = const char; _Dp = std::default_delete<const char []>]'
In file included from /usr/local/CC/gcc-4.7.4/lib/gcc/x86_64-unknown-linux-gnu/4.7.4/../../../../include/c++/4.7.4/memory:86:0,
from ./include/rocksdb/db.h:14,
from ./db/dbformat.h:14,
from ./db/db_impl.h:21,
from db/db_bench.cc:33:
That's the same issue as #284, so I just …

fix compilation error (same as fix #284)

---

util/logging.cc

The error was:
util/logging.cc: In function 'int rocksdb::AppendHumanMicros(uint64_t, char*, int)':
error: util/logging.cc:41:39: integer overflow in expression [-Werror=overflow]
} else if (micros < 1000000l * 60 * 60) {
^
error: util/logging.cc:41:39: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

Fix interger overflow on i386 arch

---

build_tools/build_detect_platform

On Centos 6, you need to explicitely include linux/falloc.h which is
where the  FALLOC_FL_* flags are defined. Otherwise, the fallocate()
support test defined in build_detect_platform will fail.
Signed-off-by: Pooya Shareghi <shareghi@gmail.com>

Added falloc.h in build_detect_platform

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/ColumnFamilyDescriptor.java
java/src/main/java/org/rocksdb/DBOptions.java
java/src/main/java/org/rocksdb/DBOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/DBOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

Summary:
- Removed deprecated ColumnFamilyDescriptor constructor methods
- Removed deprecated skipLogErrorOnRecovery methods
- Removed deprecated tableCacheRemoveScanCountLimit methods
Test Plan:
make rocksdbjava
make jtest
Reviewers: yhchiang, adamretter, ankgup87
Differential Revision: https://reviews.facebook.net/D37191

[RocksJava] Remove deprecated methods

---

java/benchmark/src/main/java/org/rocksdb/benchmark/DbBenchmark.java

1. Correct time conversions
2. Make compile again after deprecated option was removed

Small fixes to Java benchmark

---

Makefile

Includes the LDFLAGS so that the correct libraries will be linked.  This links rt to resolve the issue https://github.com/facebook/rocksdb/issues/606.

Add LDFLAGS to Java static library

---

db/c.cc
db/c_test.c
include/rocksdb/c.h

this patch does the same thing but makes clang happy, re: https://github.com/facebook/rocksdb/pull/621 it also had a gripe about `size_t` <-> `int`. clang needs some vicodin

C: add support for WriteBatch SliceParts params

---

java/Makefile

This will check if the dependencies are present in a local maven repository and use those first before attempting to download from the web.

Resolve Java test dependencies from local maven repo if present

---

java/rocksjni/options.cc
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java
java/src/main/java/org/rocksdb/Options.java
java/src/test/java/org/rocksdb/ColumnFamilyOptionsTest.java
java/src/test/java/org/rocksdb/OptionsTest.java

This PR adds JNI calls to set/get the max_table_files_size option for FIFO compaction.
The java API call is setMaxTableFilesSizeFIFO on Options and ColumnFamilyOptions. It does not directly expose the FIFO options struct since there is only one option to set.

Add JNI interface to set max_table_files_size for FIFO compaction

---

util/db_info_dumper.cc

The original "append(str, sizeof(str))" would make wal_info string truncated.

fix append bug in DumpDBFileSummary()

---

CMakeLists.txt
tools/db_sanity_test.cc

Add heap_test, merge_helper_test
Fix uninitialized pointers in db_sanity_test that cause SIGSEV when DB::Open fails in case compression is not linked.

Add missing tests, fix db_sanity

---

port/win/env_win.cc
util/auto_roll_logger.cc
util/auto_roll_logger_test.cc

* std::chrono does not provide enough granularity for microsecs and periodically emits
duplicates
* the bug is manifested in log rotation logic where we get duplicate
log file names and loose previous log content
* msvc does not imlement COW on std::strings adjusted the test to use
refs in the loops as auto does not retain ref info
* adjust auto_log rotation test with Windows specific command to remove
a folder. The test previously worked because we have unix utils installed
in house but this may not be the case for everyone.

Fix WinEnv::NowMicros

---

java/Makefile
java/rocksjni/compaction_filter.cc
java/rocksjni/options.cc
java/rocksjni/remove_emptyvalue_compactionfilterjni.cc
java/src/main/java/org/rocksdb/AbstractCompactionFilter.java
java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
java/src/main/java/org/rocksdb/RemoveEmptyValueCompactionFilter.java
src.mk
utilities/compaction_filters/remove_emptyvalue_compactionfilter.cc
utilities/compaction_filters/remove_emptyvalue_compactionfilter.h

A general compaction filter that will remove key/value pairs during compaction that have empty-values. Also added support to the Java API for using this.

RemoveEmptyValueCompactionFilter

---

Makefile

My use case is to build the rocksdb static library and tools, and
ideally I'd like to not spend time building the shared library and other
targets that I won't use.

Add a 'tools' target.

---

db/db_test.cc
port/port_posix.h
port/win/port_win.h
utilities/backupable/backupable_db.cc

VS 2013 does not support noexcept.
Complains about usage of ineteger constant within lambda requiring explicit capture.

Address noexcept and const integer lambda capture on win

---

include/rocksdb/env.h
util/file_reader_writer.cc
util/file_reader_writer.h

Summary:
This patch adds the helper functions and variables to allow a backend
implementing WritableFile to support direct IO when persisting a
memtable.
Test Plan:
Since there is no upstream implementation of WritableFile supporting
direct IO, the new behavior is disabled.
Tests should be provided by the backend implementing WritableFile.

Helper functions to support direct IO

---

port/win/env_win.cc
port/win/port_win.h
port/win/win_logger.cc
port/win/win_logger.h

This change switches Windows port files from using C runtime for file I/O to Windows API. C runtime runs into file handle limitation which creates problems when a large number of files are opened.
Changes are in Windows port files only.

Remove usage of C runtime API that has file handle limitation

---

include/rocksdb/env.h
port/win/env_win.cc
port/win/port_win.cc

Previous change for the function
https://github.com/facebook/rocksdb/commit/555ca3e7b7f06bd01dfd5e04dbb2cef5360f7917#diff-bdc04e0404c2db4fd3ac5118a63eaa4a
made use of the QueryPerformanceCounter to return microseconds values that do not repeat
as std::chrono::system_clock returned values that made auto_roll_logger_test fail.
The interface documentation does not state that we need to return
system time describing the return value as a number of microsecs since some
moment in time. However, because on Linux it is implemented using gettimeofday
various pieces of code (such as GenericRateLimiter) took advantage of that
and make use of NowMicros() as a system timestamp. Thus the previous change
broke rate_limiter_test on Windows.
In addition, the interface name NowMicros() suggests that it is …

Make WinEnv::NowMicros return system time

---

db/db_bench.cc
db/db_iter_test.cc
db/fault_injection_test.cc
include/rocksdb/env.h
port/win/env_win.cc
util/aligned_buffer.h
util/db_test_util.h
util/env_posix.cc
util/env_test.cc
util/file_reader_writer.cc
util/file_reader_writer.h
util/file_reader_writer_test.cc
util/memenv.cc
util/mock_env.cc
util/testutil.h

Summary. A change https://reviews.facebook.net/differential/diff/224721/
Has attempted to move common functionality out of platform dependent
code to a new facility called file_reader_writer.
This includes:
- perf counters
- Buffering
- RateLimiting
However, the change did not attempt to refactor Windows code.
To mitigate, we introduce new quering interfaces such as UseOSBuffer(),
GetRequiredBufferAlignment() and ReaderWriterForward()
for pure forwarding where required.
Introduce WritableFile got a new method Truncate(). This is to communicate
to the file as to how much data it has on close.
- When space is pre-allocated on Linux it is filled with zeros implicitly,
no such thing exist on Windows so we must truncate file on close.
- When operating in unbuffered mode the last page is filled …

Refactor to support file_reader_writer on Windows.

---

db/db_impl_readonly.h
db/db_test.cc

Previously, calling it caused program abort.

Override DBImplReadOnly::SyncWAL() to return NotSupported.

---

CMakeLists.txt
appveyordailytests.yml
build_tools/run_ci_db_test.ps1

Add an optimized build config switch for faster test runs
Change compiler options to introduce more opitmizations and be more inline with MS internal switches.
Make appveyor build to utilize all the avaiable cores on the VM (parallel)
Introduce new appveyor configuration for daily test runs as it would take too long
to run db_test after each checkin even in paralell.
With some exclusions we make it in 38 minutes. We currently fail to install ramdisk during the build.
Add a powershell script to faicilitate paralell run for db_test cases.

Improve CI build and build switches

---

CMakeLists.txt
appveyordailytests.yml
thirdparty.inc
util/options_parser.cc

Add missing file from CMake that breaks a build
Add port include to options_parser that makes use of snprintf
Is there a way to enforce CMake additions for internal changes that seem to come
w/o a PR?
Add notifications for daily appveyor

Improve CI build and fix Windows build breakage

---

.gitignore
Makefile
build_tools/amalgamate.py
src.mk
util/env_hdfs.cc
util/xfunc.cc

This pull request adds two new targets to the Makefile: rocksdb.cc and rocksdb.h
These files, when combined with the c.h header, are a self-contained RocksDB source distribution called an amalgamation. (The name comes from SQLite's, which is similar in concept.)
The main benefit of an amalgamation is that it's very easy to drop into a new project. It also compiles faster compared to compiling individual source files and potentially gives the compiler more opportunity to make optimizations since it can see all functions at once. (I haven't done any benchmarking so I don't know if there are actually any measurable improvements.)
rocksdb.cc and rocksdb.h are generated by a new script, amalgamate.py. A description of how amalgamate.py works is in a comment at the top of the file.
There are …

New amalgamation target

---

port/win/env_win.cc

Summary:
This mirrors  https://reviews.facebook.net/D45645
Currently, mmap returns IOError when user tries to read
data past the end of the file. This diff changes the behavior.
Now, we return just the bytes that we can, and report the size
we returned via a Slice result. This is consistent with non-mmap
behavior and also pread() system call.

Mmap reads should not return error if reading past file

---

port/win/port_win.cc
port/win/port_win.h

Mutex class in port_win incorrectly used unique_lock which is not thread-safe. Fixed it to use std::mutex itself and change condition_variable to create a unqiue_lock in local scope.
Changes are in Windows port only.

Fixing mutex to not use unique_lock

---

Makefile
java/RELEASE.md
java/crossbuild/Vagrantfile
java/crossbuild/build-linux-centos.sh

Fixed the java crossbuild jar packaging.  Prior to this change the following error would occur as a result of running <code>make jclean clean rocksdbjavastaticrelease</code> after a clean clone/checkout.  
cd java;jar -uf target/rocksdbjni-4.1.0.jar librocksdbjni-*.so librocksdbjni-*.jnilib
librocksdbjni-*.jnilib : no such file or directory
make: *** [rocksdbjavastaticrelease] Error 1
This is addressed by forcing all java artifacts (jars and libraries) to write out to the java/target directory, and then the packaging of the final jar is done within that directory.  This has the added benefit of <code>make jclean</code> actually working to clean up all of the java output files.

Fix crossbuild jar packaging

---

Makefile
java/crossbuild/build-linux-centos.sh

1) There is no need to download and install the Snappy library twice
just to get access to its header file during the compile phase.
2) Ensure that the compression library headers files used during the
compile phase are the same ones used to build the static library that
is linked into the library.

Modify the way java static builds are done so that:

---

port/win/port_win.h

Need to move debug variable under #ifndef NDEBUG. Sorry it was missed earlier.
Changes are in Windows port only.

move debug variable under ifndef NDEBUG

---

CMakeLists.txt

* add -C ${CMAKE_CURRENT_SOURCE_DIR} to git can found revision from current source directory
Tested:
* configure project by CMake 3.0.0 successfully
* configure project by command: cmake -G "Visual Studio 12 Win64"
* build solution by Visual Studio
* manually validate that file utils/build_version.cc contains valid head revision value

Error while cmake by building from zip-archive

---

CMakeLists.txt
appveyor.yml
appveyordailytests.yml

Test code errors are currently blocking Windows Release build
We do not want spend time building in Release what we can not run
We want to eliminate a source of most frequent errors when people
check-in test only code which can not be built in Release.
This feature will work only if you invoke msbuild against rocksdb.sln
Invoking it against ALL_BUILD target will attempt to build everything.

Do not build test only code and unit tests in Release builds

---

table/mock_table.cc
table/mock_table.h

On Windows two tests fail that use MockTable:
flush_job_test and compaction_job_test with the following message:
compaction_job_test_je.exe : Assertion failed: result.size() == 4,
file c:\dev\rocksdb\rocksdb\table\mock_table.cc, line 110
Investigation reveals that this failure occurs when a 4 byte
ID written to a beginning of the physically open file (main
contents remains in a in-memory map) can not be read back.
The reason for the failure is that the ID is written directly
to a WritableFile bypassing WritableFileWriter. The side effect of that
is that pending_sync_ never becomes true so the file is never flushed,
however, the direct cause of the failure is that the filesize_ member
of the WritableFileWriter remains zero. At Close() the file is truncated
to that size and the file becomes …

Fix MockTable ID storage

---

tools/write_stress.cc

char is not a valid template parameter for std::uniform_int_distribution
according to the standard. Replacing with int should be just fine.

Fix compilation problem on Windows.

---

db/memtablerep_bench.cc

Fix introduced in 2ab7065 was reverted by 18285c1.
Corrects:
db/memtablerep_bench.cc:135:22: error: ‘FLAGS_env’ defined but not used [-Werror=unused-variable]
static rocksdb::Env* FLAGS_env = rocksdb::Env::Default();
^
cc1plus: all warnings being treated as errors
Makefile:1147: recipe for target 'db/memtablerep_bench.o' failed

Fix introduced in 2ab7065 was reverted by 18285c1.

---

CMakeLists.txt
util/options_helper.cc

C4101 'identifier' : unreferenced local variable
C4189 'identifier' : local variable is initialized but not referenced
C4100 'identifier' : unreferenced formal parameter
C4296 'operator' : expression is always false

Enable compiler warnings

---

CMakeLists.txt
db/db_bench.cc
table/plain_table_factory.h
util/options.cc

Enable C4307 'operator' : integral constant overflow
Longs and ints on Windows are 32-bit hence the overflow
Enable C4309 'conversion' : truncation of constant value
Enable C4512 'class' : assignment operator could not be generated
Enable C4701 Potentially uninitialized local variable 'name' used

Enable Windows warnings C4307 C4309 C4512 C4701

---

include/rocksdb/env.h
port/win/env_win.cc
util/env_test.cc
util/file_reader_writer.cc
util/file_reader_writer.h
util/file_reader_writer_test.cc
util/io_posix.cc
util/io_posix.h
util/random.cc
util/random.h

in 64-bit.
Currently, a signed off_t type is being used for the following
interfaces for both offset and the length in bytes:
* `Allocate`
* `RangeSync`
On Linux `off_t` is automatically either 32 or 64-bit depending on
the platform. On Windows it is always a 32-bit signed long which
limits file access and in particular space pre-allocation
to effectively 2 Gb.
Proposal is to replace off_t with uint64_t as a portable type
always access files with 64-bit interfaces.
May need to modify posix code but lack resources to test it.

Make use of portable `uint64_t` type to make possible 64-bit file access

---

thirdparty.inc

This would enable people to redirect include and lib paths to the 3rd party libs such as gflags and zlib for build purposes using env vars instead of modifying thirdparty.inc

Enable override to 3rd party linkage

---

include/rocksdb/env.h

Missed this when the new call was added.
By the way, I also made a MirrorEnv implementation that takes two Env's and does all operations on both, and compares the return values and read results.  This was hugely helpful in writing my own Env implementation.. any interest upstream?
https://github.com/liewegas/ceph/blob/wip-bluestore/src/os/bluestore/MirrorEnv.h

EnvWrapper: add ReuseWritableFile

---

utilities/backupable/backupable_db.cc

Fix build error 
backupable_db.cc(1462): warning C4101: 'e' : unreferenced local variable

Fix ms version Appveyor build error

---

CMakeLists.txt
db/compaction.cc
db/db_compaction_test.cc
db/db_test.cc
db/db_test_util.cc
db/db_test_util.h
db/log_writer.cc
db/log_writer.h
port/win/env_win.cc
port/win/win_logger.cc
util/coding.h
util/options_builder.cc
utilities/document/json_document_builder.cc

* conversion from 'size_t' to 'type', by add static_cast
* extend type from int to int64_t
Tested:
* by build solution on Windows, Linux locally,
* run tests

Enable C4267 warning

---

src.mk
util/env_posix.cc
util/thread_posix.cc
util/thread_posix.h

Summary: This patch moves all posix thread logic to separate library.
The motivation is to allow another environments to easily reuse posix
threads. HDFS wraps already posix threads; this split would simplify
this code.
Test Plan: No new functionality is added to posix Env or the threading
library, thus the current tests should suffice.

Move posix threads into a library

---

CMakeLists.txt

There are two tests missing from the Windows build because they were added after it was developed.  This includes them in Windows builds.
db/compaction_iterator_test
util/delete_scheduler_test
Both tests appear to be passing.

Add compaction_iterator and delete_scheduler tests to Windows build

---

util/compression.h

The code had conversion to double then casting to size_t
and then casting uint32_t which caused compiler warning (VS15).

Prefer integer arithmetics

---

CMakeLists.txt
Makefile
include/rocksdb/env.h
include/rocksdb/utilities/env_mirror.h
src.mk
utilities/env_mirror.cc
utilities/env_mirror_test.cc

This is an Env implementation that mirrors all file-related activity on two different
backend Env's.  It's been very helpful while debugging a custom Env implementation.

implement EnvMirror

---

include/rocksdb/delete_scheduler.h

As Title
c:\projects\rocksdb\include\rocksdb\delete_scheduler.h(63): error C2039: 'shared_ptr' : is not a member of 'std' [C:\projects\rocksdb\build\delete_scheduler_test.vcxproj]

Fix appVeyor Build problem

---

db/db_compaction_test.cc

~~~
db/db_compaction_test.cc:604:58: error: implicit conversion loses integer precision: 'unsigned long long' to 'const int'
[-Werror,-Wshorten-64-to-32]
const int key_len = compact_opt.output_file_size_limit / 5;
~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
~~~

Fix clang warning regarding implicit conversion

---

hdfs/env_hdfs.h
util/env_hdfs.cc

* include `util/string_util.h` which contains `ToString` macro in `env_hdfs.cc` to fix ToString not declared error
* implement `LinkFile` function by returning a NotSupported status to avoid LinkFile undefined reference error, because HdfsEnv class defines LinkFile function without implementing it and actually, HDFS does not provide such API in c.

Fix build error with hdfs

---

include/rocksdb/status.h

Status is a class which is frequently returned by value from functions.
Making it movable avoids 99% of the copies automatically
on return by value.

Make Status moveable

---

db/db_test.cc

~~~
db/db_test.cc:4780:10: error: moving a local object in a return statement prevents copy elision
[-Werror,-Wpessimizing-move]
return std::move(file_numbers);
^
db/db_test.cc:4780:10: note: remove std::move call here
return std::move(file_numbers);
^~~~~~~~~~            ~
~~~
`-Wpessimizing-move` was introduced in clang 3.7.

Fix clang warning

---

db/compaction_job.cc

If breaking the loop when `subcompactions==1`, the `sum` will be 0 and size of the last sub-compaction is incorrect.

Fix computation of size of last sub-compaction

---

db/db_log_iter_test.cc
db/wal_manager.cc
db/wal_manager_test.cc
util/options_sanity_check.h
utilities/backupable/backupable_db.cc
utilities/document/json_document.cc
utilities/flashcache/flashcache.cc

I try to compile using clang 3.7 under Arch Linux.
73b175a7738a53cf9a906ef1389962378c7ddf72 fixes all warning regarding `std::move`.
1aef02f67b0129784cf8373d2f82e4c6742fc94c fixes a compile error. Actually the original code is valid. But clang uses `libstdc++` under Linux, and `libstdc++` does not proper implement `std::unordered_map` (it lacks user-provided default constructor, see https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/unordered_map.h#L132). Defining const object without user-provided default constructor is invalid (http://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a), and clang rejects to compile (but gcc accepts it). So I create this commit as a workaround to let it compiled.

Fix clang warnings

---

include/rocksdb/env.h
util/env_hdfs.cc

There is no way we can use HDFSEnv even if we compile with HDFS and install as shared_lib.
implementing a factory method that creates the HDFS environment.

add a factory method for creating hdfs env

---

CMakeLists.txt
db/column_family.cc
db/db_impl.cc
db/db_test.cc
db/repair.cc

Currently Windows build is broken because of Warning C4351. Disable the warning before figuring out the right way to fix it.

Disable Visual Studio Warning C4351 and Add some type casts to suppress warnings

---

table/block_based_table_reader.cc
table/table_test.cc

PrefixMayMatch previously seeked in the prefix index using an internal
key with a sequence number of 0. This would cause the prefix index seek
to fall off the end if the last key in the index had a user-key greater
than or equal to the key being looked for. Falling off the end of the
index in turn results in PrefixMayMatch returning false if the index is
in memory.

Fix index seeking in BlockTableReader::PrefixMayMatch.

---

db/plain_table_db_test.cc

Use constructor style initialization instead of a cast for
simplicity.

Fix compile error.

---

util/crc32c.cc

This fixes the compile error on 32-bit mentioned in issue #634.  This allows successful compilation of 32 bit library on Linux.
Debug compilation on OSX still fails because it declares -Wshorten-64-to-32, so you have to turn off warnings as errors to compile.  It does compile after that.
Note that it doesn't appear that the test cases were operational in 32 bit, so I can't evaluate whether any test cases fail as a result of this change.

fix a compile error on 32-bit (fixes #634)

---

INSTALL.md
Makefile
build_tools/build_detect_platform

These simple changes are required to allow builds on ppc64[le] systems
consistent with X86. The Makefile now recognizes both ppc64 and ppc64le, and
in the absence of PORTABLE=1, the code will be built analogously to the X86
-march=native.
Note that although GCC supports -mcpu=native -mtune=native on POWER, it
doesn't work correctly on all systems. This is why we need to get the actual
machine model from the AUX vector.

Simple changes to support builds for ppc64[le] consistent with X86

---

CMakeLists.txt

@yuslepukhin Here is fix for generated GenerateBuildVersion.vcxproj when one builds on different locale than english. The problem is that date and time CLI utilities generates different format so that REGEX in CMake does not work.
It also contains fix for util/auto_roll_logger.cc that was recently moved to different directory.
facebook/rocksdb#868

Fixing generated GenerateBuildVersion.vcxproj on non English locale

---

include/rocksdb/options.h
port/win/env_win.cc

This change impacts only non-buffered I/O on Windows.
Currently, there is a buffer per RandomAccessFile
instance that is protected by a lock. The reason we
maintain the buffer is that non-buffered I/O requires an aligned
buffer to work.
XPerf traces demonstrate that we accumulate a considerable
wait time while waiting for that lock.
This change enables to set random access buffer size to zero
which would indicate a per request allocation.
We are expecting that allocation expense would be much less than
I/O costs plus wait time due to the fact that the memory heap
would tend to re-use page aligned allocations especially with the
use of Jemalloc.
This change does not affect buffer use as a read_ahead_buffer for
compaction purposes.

Enable per-request buffer allocation in RandomAccessFile

---

db/db_impl.cc
include/rocksdb/statistics.h

With this change, we know the value size distribution in the DB. 
This is a very important piece of info for optimizing DB options, e.g. selecting block_size according to the value size.

Add histogram for value size per operation

---

db/auto_roll_logger.cc
port/win/env_win.cc

@yuslepukhin Making use of GetSystemTimePreciseAsFileTime dynamic to not break compatibility with Windows 7. The issue with rotated logs was fixed other way.
#726

Making use of GetSystemTimePreciseAsFileTime dynamic

---

CMakeLists.txt

This partially addresses issue https://github.com/facebook/rocksdb/issues/935
testutil.cc and testharness.cc could not be moved out at this time
as they are used by 4 benchmarks in release builds.

Move out of release build some test code

---

db/db_iter.cc

Use user_comparator when comparing against iterate_upper_bound.

---

Makefile

-momit-leaf-frame-pointer is only supported on certain archs.
Detect this automatically based on which flags the compiler
understands.

build: Improve -momit-leaf-frame-pointer usage

---

utilities/backupable/backupable_db.cc

c:\projects\rocksdb\utilities\backupable\backupable_db.cc(1619): warning C4101: 'e' : unreferenced local variable [C:\projects\rocksdb\build\rocksdblib.vcxproj]

Fix Windows build

---

tools/ldb_cmd.cc
tools/ldb_cmd.h

Adding an option to ldb to make it possible to dump keys only, without values.

added --no_value option to ldb scan to dump key only

---

CMakeLists.txt
src.mk
tools/db_bench_tool.cc
util/histogram.cc
util/histogram.h
util/histogram_test.cc
util/histogram_windowing.cc
util/histogram_windowing.h

Link to Issue https://github.com/facebook/rocksdb/issues/1009 
@kradhakrishnan @siying @igorcanadi
Changes in this patch
- Replaced histogram counter type uint64_t with std::atomic_uint_fast64_t to support update atomicity
- Extracted an interface (class Histogram) for HistogramImpl and HistogramWindowingImpl and wrapped the data in struct HistogramStat 
- Introduced HistogramWindowingImpl class for supporting real-time histogram caculation
- Extended histogram_test for better coverage
I had run performance tests to verify no regression is introduced. 
Let me know if there is anything I can do to make it easier for your review.

Histogram Concurrency Improvement and Time-Windowing Support

---

util/histogram.cc

11:30:29 from ./util/histogram.h:13,
11:30:29 from util/histogram.cc:18:
11:30:29 util/histogram.cc: In member function ‘void rocksdb::HistogramStat::Add(uint64_t)’:
11:30:29 util/histogram.cc:104:40: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
11:30:29 assert(index < num_buckets_ && index >= 0);
11:30:29 ^

Fix FB internal CI build failure

---

include/rocksdb/options.h

As discussed in #1032. I did my best to be technically accurate without overwhelming the user with details.

Improve documentation of the allow_os_buffer parameter.

---

port/win/port_win.cc
thirdparty.inc

calls. #ifdef in the source code and make this a default build option.

Latest versions of Jemalloc library do not require je_init()/je_unint()

---

util/histogram_windowing.cc

@kradhakrishnan
In file included from unity.cc:109:0:
util/histogram_windowing.cc:18:31: error: redefinition of â€˜const rocksdb::HistogramBucketMapper rocksdb::{anonymous}::bucketMapperâ€™
const HistogramBucketMapper bucketMapper;
^
In file included from unity.cc:108:0:
util/histogram.cc:77:31: note: â€˜const rocksdb::HistogramBucketMapper rocksdb::{anonymous}::bucketMapperâ€™ previously declared here
const HistogramBucketMapper bucketMapper;
valgrind error:
==627965== 5,768 bytes in 1 blocks are definitely lost in loss record 10 of 10
==627965== at 0x4C2B9C4: operator new (in /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==627965== by 0x5B230F: rocksdb::HistogramWindowingImpl::HistogramWindowingImpl() (histogram_windowing.cc:23)
==627965== by …

Fix in HistogramWindowingImpl

---

db/db_impl.cc
db/repair.cc
db/transaction_log_impl.cc
db/wal_manager.cc
db/write_batch.cc
db/write_batch_internal.h
tools/ldb_cmd.cc

In all the places where log records are read, there was a check that record.size() should not be less than 12.
This "magic number" seems to be the WriteBatch header (8 byte sequence and 4 byte count). 
Replaced all the places where "12" was used by WriteBatchInternal::kHeader.

Remove the Magic number 12 used in record size checks

---

java/Makefile
java/benchmark/src/main/java/org/rocksdb/benchmark/DbBenchmark.java
java/src/main/java/org/rocksdb/AbstractSlice.java
java/src/main/java/org/rocksdb/util/BytewiseComparator.java
java/src/main/java/org/rocksdb/util/DirectBytewiseComparator.java
java/src/main/java/org/rocksdb/util/ReverseBytewiseComparator.java
java/src/test/java/org/rocksdb/util/BytewiseComparatorTest.java

These changes reimplement the Bytewise and Reverse Bytewise comparators from C++ in Java and allow custom Java comparators to be specified to `jdb_bench` for benchmarking.
I have performed some initial benchmarks on comparing the performance of C++ and Java comparators.
My machine is: `Apple MacBook Pro (Retina, 15-inch, Mid 2015)` / `2.8 GHz Intel Core i7` / `16 GB 1600 MHz DDR3` / `OS X El Capitain 10.11.3 (15D21)`.
Summary
=======
The Java Comparators are hugely less-efficient that their C++ counterparts, this is particularly pronounced when only a single thread is used.
Single-threaded writes (`fillseq`) are `~6x` faster whilst random reads (`readrandom`) are `105x` faster when using a C++ comparator as opposed to the equivalent Java comparator.
Multi-threaded (4 threads) writes …

Benchmark Java comparator vs C++ comparator

---

utilities/spatialdb/spatial_db.cc

fix wrong assignment of level0_stop_writes_trigger in spatialdb's function GetColumnFamilyOptions.

fix wrong assignment of level0_stop_writes_trigger in spatialdb

---

hdfs/README

We tested to use the HDFS environment for rocksDB backup. From our experience, the hdfsConnect() will constantly crash on large rocksdb instances (1.5-3G).  It is related to this JDK6 bug:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6964776
After we change to jvm7, the issue goes away. So change readme to suggest people use java7 to run the hdfs environemnt.

instructing people to use java7 for hdfs environment

---

CMakeLists.txt
db/compaction_job_stats_test.cc
db/db_test.cc
db/db_wal_test.cc
include/rocksdb/options.h
port/win/port_win.h
port/win/xpress_win.cc
port/win/xpress_win.h
port/xpress.h
table/block_based_table_builder.cc
table/format.cc
table/format.h
table/table_test.cc
thirdparty.inc
tools/db_bench_tool.cc
tools/db_stress.cc
tools/ldb_cmd.cc
tools/sst_dump_tool.cc
util/compression.h
util/options_helper.h
util/options_test.cc

Comparable with Snappy on comp ratio.
Implemented using Windows API, does not require external package.
Avaiable since Windows 8 and server 2012.
Use -DXPRESS=1 with CMake to enable.

Introduce XPRESS compresssion on Windows.

---

db/c.cc
include/rocksdb/c.h

Exposes a couple of more options. `rocksdb_options_set_db_write_buffer_size` already exists in `c.cc` but on in `c.h`, so just exposing it.

expose more options in the c api

---

db/c.cc
include/rocksdb/c.h

This is useful for C libraries wrapping rocksdb, especially for tests that create a real rocksdb instance.

rocksdb_create_mem_env to allow C libraries to create mem env

---

db/c.cc
db/c_test.c
include/rocksdb/c.h

Exposing `PurgeOldBackups` for C libraries.

rocksdb_backup_engine_purge_old_backups for C libraries

---

db/db_iter.cc
db/prefix_test.cc

This avoids excessive iteration in tombstone fields.

Use prefix_same_as_start to avoid iteration in FindNextUserEntryInternal.

---

port/win/env_win.cc

This reverts commit b54c34742412af0001a69c2f7d909bc05e1ea71f.
Revert async file handle change as it causes failures with appveyor

Revert "Use async file handle for better parallelism (#1049)"

---

db/column_family.cc

Using explicit 64-bit type in conditional in platforms above 32-bits
std::conditional does not appear to short circuit before evaluating the third template arg which results in an error because the constant value does not fit in a 32-bit size_t.  This is a warning in a linux environment but an error in Mac OSX
The solution is to just make the third argument type explicitly 64-bit.  The entire expression then either becomes a 32-bit constant or a 64-bit constant holding a 32-bit value, but in either case is assignable to a 32-bit size_t.
This works correctly in the following cases:
32-bit: a 32-bit value will be assigned to a 32-bit size_t.
64-bit: size_t and uint64_t are the same size so the assignment is fine.
\>64-bit: size_t is larger than uint64_t so the assignment is fine.

Fix #1110, 32-bit build failure on Mac OSX

---

tools/sst_dump_tool.cc

Update:
"Size is not shown" is not printed.
./sst_dump_test result after the update:
...
Compression: kNoCompression Size: 28056
Compression: kSnappyCompression Size: 7066
Compression: kZlibCompression Size: 3868
Compression: kBZip2Compression Size: 2896
Unsupported compression type: kLZ4Compression. 
Unsupported compression type: kLZ4HCCompression. 
Unsupported compression type: kXpressCompression. 
Unsupported compression type: kZSTDNotFinalCompression.
...
The previous information about the pull request:
Included util/compression.h in headers
Added if-else with the condition CompressionTypeSupported in the for loop of ShowAllCompressionSizes
Test plan is to run ./sst_dump_test to verify the code of the pull request.

Say that an unsupported compression type is not supported in ShowAllCompressionSizes

---

HISTORY.md

A couple "New Features" headers needed a blank line before them.

Fix formatting of HISTORY.md

---

CMakeLists.txt
port/win/env_default.cc
port/win/env_win.cc
port/win/env_win.h
port/win/io_win.cc
port/win/io_win.h
port/win/port_win.h
port/win/win_logger.cc
port/win/win_logger.h

For ease of reuse and customization as a library
without wrapping.
WinEnvThreads is a class for replacement.
WintEnvIO is a class for reuse and behavior override.
Added private virtual functions for custom override
of fallocate pread for io classes.

Split WinEnv into separate classes.

---

port/stack_trace.cc

So set it to generate empty routines

stack_trace,cc: The current Stacktrace code does not compile for FreeBSD

---

java/rocksjni/loggerjnicallback.cc
java/src/test/java/org/rocksdb/LoggerTest.java

WARN level logging is now correctly logged at WARN level via the Java API, previously it was mistakenly logged at FATAL level.

Previously WARN level logging became FATAL level logging in the Java API

---

util/options_builder.cc

GCC 5.4 will complain (see also options_parser.cc):
/home/abuild/rpmbuild/BUILD/arangodb-3.0.0r1/3rdParty/rocksdb/rocksdb/util/options_builder.cc: In function 'rocksdb::CompactionStyle rocksdb::{anonymous}::PickCompactionStyle(size_t, int, int, uint64_t)':
/home/abuild/rpmbuild/BUILD/arangodb-3.0.0r1/3rdParty/rocksdb/rocksdb/util/options_builder.cc:29:7: error: 'log' is not a member of 'std'
std::log(target_db_size / write_buffer_size) / std::log(kBytesForLevelMultiplier)));
^
/home/abuild/rpmbuild/BUILD/arangodb-3.0.0r1/3rdParty/rocksdb/rocksdb/util/options_builder.cc:29:7: note: suggested alternative:
In file included from /usr/include/features.h:365:0,
from /usr/include/math.h:26,
from /home/abuild/rpmbuild/BUILD/arangodb-3.0.0r1/3rdParty/rocksdb/rocksdb/util/options_builder.cc:6: …

Fix for GCC 5.4

---

include/rocksdb/write_batch.h
java/rocksjni/write_batch.cc
java/rocksjni/write_batch_with_index.cc
java/src/main/java/org/rocksdb/AbstractWriteBatch.java
java/src/main/java/org/rocksdb/WriteBatch.java
java/src/main/java/org/rocksdb/WriteBatchInterface.java
java/src/main/java/org/rocksdb/WriteBatchWithIndex.java
java/src/test/java/org/rocksdb/WriteBatchTest.java
java/src/test/java/org/rocksdb/WriteBatchWithIndexTest.java

Implemented:
1. `WriteBatch#setSavePoint`
2. `WriteBatch#rollbackToSavePoint`
3. `WriteBatchWithIndex#setSavePoint`
4. `WriteBatchWithIndex#rollbackToSavePoint`

Expose save points in Java WriteBatch and WBWI

---

java/rocksjni.pom

using gmaven property so that script is not broken by embedding unescaped Windows-style path
Please check the issue description.

fixes #1212: rocksdbjni maven build does not escape slashes in groovy script

---

java/CMakeLists.txt

specifying minimum cmake version so that no warning has to be suppressed

fixes #1210: rocksdb/java/CMakeLists.txt lacks cmake_minimum_required

---

.gitignore
db/db_test.cc
db/plain_table_db_test.cc
db/table_properties_collector_test.cc
db/version_set.cc
include/rocksdb/statistics.h
table/block_based_table_builder.cc
table/block_based_table_reader.cc
table/block_based_table_reader.h
table/cuckoo_table_builder_test.cc
table/cuckoo_table_reader.cc
table/format.cc
table/format.h
table/meta_blocks.cc
table/meta_blocks.h
table/plain_table_reader.cc
table/table_test.cc
tools/sst_dump_tool.cc
util/coding.h

Added new statistics that our team wants to be able to track:
Tickers:
```
NUMBER_BLOCK_COMPRESSED      // number of compressions that occur
NUMBER_BLOCK_DECOMPRESSED    // number of decompressions that occur
```
Histograms:
```
BYTES_COMPRESSED             // tracks size of compressions
BYTES_DECOMPRESSED           // tracks size of decompressions
COMPRESSION_TIMES_NANOS      // tracks time spent on each compression
DECOMPRESSION_TIMES_NANOS    // tracks time spent on each decompression
```
As can be seen from the change list, adding these statistics required modification of existing function definitions. To track the new statistics, an environment pointer and statistics pointer are required in the `WriteBlock()` function of `block_based_table_builder.cc` and the …

New Statistics to track Compression/Decompression

---

Makefile

The tests run by `make check` require Bash. On Debian you'd need to run
the test as `make SHELL=/bin/bash check`. This commit makes it work on
all POSIX compatible shells (tested on Debian with `dash`).

Remove bashism from `make check`

---

db/db_iterator_test.cc
db/db_sst_test.cc
utilities/simulator_cache/sim_cache.cc

The `%zu` and `%z` format specifiers do not work on Windows. This change replaces two instances of `%zu` that managed to sneak in with the `ROCKSDB_PRIszt` macro defined in each port header file.

Remove %z Format Specifier and Fix Windows Build of sim_cache.cc

---

java/rocksjni/options.cc
java/rocksjni/rocksjni.cc
java/rocksjni/ttl.cc

using new keyword to create variable-size arrays in order to satisfy most of the compilers

fixes 1220: rocksjni build fails on Windows due to variable-size array declaration

---

tools/ldb_cmd.cc

getline on std::cin can be very inefficient when ldb is loading large values, with high CPU usage in libc _IO_(un)getc, this is because of the performance penalty that comes from synchronizing stdio and iostream buffers.
See the reproducers and tests in #1133 .
If an ifstream on /dev/stdin is used (when available) then using ldb to load large values can be much more efficient.
I thought for ldb load, that this approach is preferable to using <cstdio> or std::ios_base::sync_with_stdio(false).
I couldn't think of a use case where ldb load would need to support reading unbuffered input, an alternative approach would be to add support for passing --input_file=/dev/stdin.
I have a CLA in place, thanks.
The CI tests were failing at the time of https://github.com/facebook/rocksdb/pull/1156, so …

ldb load, prefer ifsteam(/dev/stdin) to std::cin

---

java/src/main/java/org/rocksdb/NativeLibraryLoader.java
java/src/test/java/org/rocksdb/NativeLibraryLoaderTest.java

overriding existing library in tmp folder

fixes 1228: rockdbjni loadLibraryFromJarToTemp fails when file is already present

---

CMakeLists.txt

quoting the las argument of string REGEXP REPLACE function

fixes 1230: Error:string sub-command REGEX, mode REPLACE needs at least 6 arguments total to command

---

java/rocksjni/loggerjnicallback.cc
java/rocksjni/loggerjnicallback.h

In our application build atop RocksDB we would occasionally see `SIGSEGV` when background flushes were run.
This was caused by the call to `env->FindClass("org/rocksdb/InfoLogLevel")` in `portal.h` returning `nullptr`. That would happen if the thread calling that was not known to the JVM, e.g. it was created from C++ by `pthread_create` or similar, calling `FindClass` from that unknown thread means the JVM cannot find the classloader and so does not locate the class. See also http://developer.android.com/training/articles/perf-jni.html#faq_FindClass
This PR fixes that by caching Global References to the objects that are needed for logging when the logger is first instantiated.
For reference, the `SIGSEGV`'s that we were seeing looked like:
```
Stack: …
```

Bugfix to ensure that logging can be achieved from any thread

---

Makefile
java/Makefile

* Separate targets for the compilation and execution steps of `make jtest`, now provides in addition:
* make `jtest_compile`
* make `jtest_run`
* This is useful for running all Java tests or just a single Java test after compilation.
* Also useful when compiling with ASAN: https://github.com/facebook/rocksdb/wiki/JNI-Debugging

More granular steps in the Makefile for Java Tests

---

java/samples/src/main/java/RocksDBSample.java

Fix a typo in `java/samples`:
Correct `geHistogramData()` -> `getHistogramData()`

Correct geHistogramData() -> getHistogramData()

---

util/arena.cc

From the Linux manual:
MAP_ANONYMOUS
The  mapping  is  not  backed  by any file; its contents
are initialized to zero.  The fd and offset arguments are
ignored; however, some implementations require fd to be -1
if MAP_ANONYMOUS (or MAP_ANON) is specified, and portable
applications  should  ensure  this.
FreeBSD is such a case, it wil just return an error.
Signed-off-by: Willem jan Withagen <wjw@digiware.nl>

util/arena.cc: FreeBSD: More portable use of mmap(MAP_ANON)

---

include/rocksdb/options.h

Users shouldn't reply on -> users shouldn't rely on

Fixed typo

---

java/CMakeLists.txt

using an platform-neutral file(MAKE_DIRECTORY ${DIR}) function

fixes 1215: execute_process(COMMAND mkdir ${DIR}) fails to create a directory with cmake on Windows

---

include/rocksdb/status.h
java/Makefile
java/rocksjni/portal.h
java/rocksjni/rocksdb_exception_test.cc
java/src/main/java/org/rocksdb/RocksDBException.java
java/src/main/java/org/rocksdb/Status.java
java/src/test/java/org/rocksdb/RocksDBExceptionTest.java
src.mk

Stops meaningful function result Status from the C++ API being converted into a munged Java String; Instead provides a `Status` object which can be retrieved from `RocksDBException`.
Closes https://github.com/facebook/rocksdb/issues/1250

Add Status to RocksDBException 

---

Makefile

Snappy is no longer downloadable from Google Code, instead you have to retrieve it via GitHub.

Update the download location of Snappy

---

utilities/persistent_cache/persistent_cache_bench.cc

We mixed using `uint64_t` and `size_t` somewhere, which leads to a warning in Mac.
Although Travis itself was not working normally, this PR does not break our Linux build (Windows build seems to break somewhere else).

Fix Mac build failure

---

include/rocksdb/convenience.h

StringToMap() becomes handy to use together with DB::SetOptions(), since SetOptions() accepts options in the std::unoroder_map format.

Expose Utility function StringToMap()

---

db/db_test.cc
include/rocksdb/statistics.h
table/format.cc
util/instrumented_mutex.cc

Currently, setting the stats level to `kExceptTimeForMutex` will also turn off "detailed timers" (compression timing), while setting it to `kExceptDetailedTimers` will cause mutex timers to run. This is because `InstrumentedMutex` checks if stats should be reported with:
`stats->stats_level_ != kExceptTimeForMutex`
And compression stats are controlled by:
`stats->stats_level_ > kExceptDetailedTimers` (the value of kExceptTimeForMutex is less than kExceptDetailedTimers)
This pull request corrects this behavior so that `kExceptDetailedTimers` turns off both compression and mutex statistics while `kExceptTimeForMutex` leaves compression stats on. To keep compression stats off by default, the default stats level is also changed to `kExceptDetailedTimers`.

Ensure Correct Behavior of StatsLevel kExceptDetailedTimers and kExceptTimeForMutex 

---

CMakeLists.txt
db/db_impl.cc
src.mk
table/block_test.cc

CI for Windows (AppVeyor) fails since CMakeLists.txt has a line 'util/mutable_cf_options.cc' which does not exist currently.
```
CMake Error at CMakeLists.txt:307 (add_library):
Cannot find source file:
util/mutable_cf_options.cc
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx
CMake Error: CMake can not determine linker language for target: rocksdbli
```

Fix build error on Windows (AppVeyor)

---

java/rocksjni/rocksjni.cc
java/src/main/java/org/rocksdb/RocksDB.java

See https://github.com/facebook/rocksdb/pull/1247#issuecomment-237323012 for further information on the requirement.
The only potential concern here is perhaps that previously we used `JNIEnv::GetByteArrayElements` which *may* or *may not* have made a copy of the entire array, whereas we now use `JNIEnv::GetByteArrayRegion` which explicitly makes a copy of part of the array (or the entire array) that we are interested in.
From what I have read, it is likely that the JVM would have made a copy when calling `GetByteArrayElements`, but this is not certain and would have varied from platform to platform. For those who want to avoid the transient memory increase of copying data, we can look at adding support for `DirectSlice` to these operations in future.

Allow an offset as well as a length to be specified for byte[] operations in RocksJava JNI

---

db/c.cc
db/c_test.c

Fixes #1296 
Since these memtable_factories are shared_ptrs, whenever options is destroyed the static pointer becomes invalid. Any further use of these functions uses an invalid pointer. I eliminated this pattern from the C api, since there isn't much benefit to this in the first place.
I also added a test that fails without the fix. I don't know if it's to trivial to include, though.

Fix C api memtable rep bugs.

---

db/db_impl.cc

If log recycling is enabled with the rocksdb (recycle_log_file_num=16)
db->Writebatch is erroring out with keynotfound after ~5-6 hours of run
(1M seq but can happen to any workload I guess).See my detailed bug
report here (https://github.com/facebook/rocksdb/issues/1303).
This commit is the fix for this, a check is been added not to delete
the log file if it is already there in the recycle list.
Test Plan:
Unit tested it and ran the similar profile. Not reproducing anymore.

Bug fix on log recycle

---

db/builder.cc
db/builder.h
db/compaction_job.cc
db/table_properties_collector_test.cc
table/sst_file_writer.cc
table/table_builder.h
table/table_reader_bench.cc
table/table_test.cc
tools/sst_dump_test.cc
tools/sst_dump_tool.cc

For issue: https://github.com/facebook/rocksdb/issues/1333
I also modified other relevant code.

Add TableBuilderOptions::level and relevant changes

---

table/adaptive_table_factory.cc

when use "NewAdaptiveTableFactory()", i.e. no parameters, so table_factory_to_write, block_based_table_factory,  plain_table_factory, cuckoo_table_factory use the default value "nullptr"
NewAdaptiveTableFactory() => AdaptiveTableFactory(table_factory_to_write, block_based_table_factory, plain_table_factory, cuckoo_table_factory):
if (!table_factory_to_write_) {
table_factory_to_write_ = block_based_table_factory_;
}
if (!plain_table_factory_) {
plain_table_factory_.reset(NewPlainTableFactory());
}
if (!block_based_table_factory_) {
block_based_table_factory_.reset(NewBlockBasedTableFactory());
}
if (!cuckoo_table_factory_) {
cuckoo_table_factory_.reset(NewCuckooTableFactory());
}
table_factory_to_write_ = nullptr
plain_table_factory_ != nullptr
block_based_table_factory_ != nullptr …

solve the problem of table_factory_to_write_ = nullptr

---

Makefile
db/db_impl.cc
db/db_impl.h
db/db_wal_test.cc

Summary:
Revert the behavior where we don't read sequence id from WAL, but increase it as we replay the log. We still keep the behave for 2PC for now but will fix later.
This change fixes github issue 1339, where some writes come with WAL disabled and we may recover records with wrong sequence id.
Test Plan: Added unit test.
Subscribers: andrewkr, dhruba
Differential Revision: https://reviews.facebook.net/D64275

Recover same sequence id from WAL

---

db/compact_files_test.cc

Remove the L0 compaction slow down and stopping conditions to not end up with a test that never finish

Fix CompactFilesTest.ObsoleteFiles timeout

---

db/db_impl.cc
db/db_options_test.cc

Summary: We didn't recompute compaction score on SetOptions, and end up not having compaction if no flush happens afterward. The PR fixing it.
Test Plan: See unit test.
Differential Revision: https://reviews.facebook.net/D64167

Recompute compaction score on SetOptions

---

CMakeLists.txt
cmake/modules/FindJeMalloc.cmake
cmake/modules/Findsnappy.cmake
tools/CMakeLists.txt
utilities/persistent_cache/hash_table_bench.cc

cmake support for linux and osx

---

java/rocksjni/write_batch_test.cc

Fixing unused variable for release JNI build:
V=1 make rocksdbjavastatic
java/rocksjni/write_batch_test.cc: In function ‘_jbyteArray* Java_org_rocksdb_WriteBatchTest_getContents(JNIEnv*, jclass, jobject)’:
java/rocksjni/write_batch_test.cc:63:10: warning: unused variable ‘parsed’ [-Wunused-variable]
bool parsed = rocksdb::ParseInternalKey(iter->key(), &ikey);
^
@adamretter Can you please review?

Fixing JNI release build for gcc

---

include/rocksdb/c.h

Added rocksdb_options_set_memtable_prefix_bloom_size_ratio function implemented in c.cc but not exported via c.h

update of c.h

---

util/log_write_bench.cc

Hello and thank you for RocksDB,
I noticed when using log_write_bench that writes were always 88 bytes:
```
> strace -e trace=write ./log_write_bench -num_records 2 2>&1 | head -n 2
write(3, "\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371"..., 88) = 88
write(3, "\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371\371"..., 88) = 88
```
```
> strace -e trace=write ./log_write_bench -record_size 4096 -num_records 2 2>&1 | head -n 2
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 88) = 88
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 88) = 88
```
I think this should be:
``` …
```

Fix record_size in log_write_bench, swap args to std::string::assign.

---

tools/check_format_compatible.sh

Some older tags don't run GCC 4.8 with FB internal setting. Fixed them and created branches. Change the format compatible script accordingly.
Also add more releases to check format compatibility.

Fix check_format_compatible.sh and add more releases

---

java/Makefile

Junit and our code generate lots of warning if "-Xcheck:jni" is on and force Travis to fail as the logs are too long.

Fix java Build by disabling "-Xcheck:jni"

---

utilities/memory/memory_test.cc

Summary: Auto-compactions will change memory usage of DB but memory_test
didn't take it into account. This PR disable auto compactions in the
test and hopefully it fixes its flakyness.
Test Plan:
UBSAN build used to catch the flakyness. Run `make ubsan_check` and it
passes.

Disable auto compactions in memory_test and re-enable the test

---

tools/regression_test.sh

Summary:
Fix a bug that mistakenly disable regression_test.sh to update commit
Test Plan:
regression_test.sh

Fix a bug that mistakenly disable regression_test.sh to update commit

---

db/db_test.cc

The verification condition of the test DBTest.RepeatedWritesToSameKey doesn't hold anymore after 3ce3bb3da2486c2c18a332128dda7c05a91abb85.
Disable the test for now before we find a way to replace it.
Test Plan: Run the test and make sure it is disabled.

Disable DBTest.RepeatedWritesToSameKey

---

CMakeLists.txt
Makefile
util/build_version.cc.in

* util/build_verion.cc.in: add this file, so cmake and make can share the
template file for generating util/build_version.cc.
* CMakeLists.txt: also, cmake v2.8.11 does not support file(GENERATE ...),
so we are using configure_file() for creating build_version.cc.
* Makefile: use util/build_verion.cc.in for creating build_version.cc.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

Makefile: generate util/build_version.cc from .in file

---

CMakeLists.txt

this breaks the cross-compiling, and we can not assume that the building
machine and the target machine share the same CPU spec.
Signed-off-by: Kefu Chai <kchai@redhat.com>

cmake: drop "-march=native" from CXX_FLAGS

---

table/block.h
util/arena.cc
util/env_test.cc

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>

FreeBSD: malloc_usable_size is in <malloc_np.h>

---

HISTORY.md
db/memtable.cc
db/merge_context.h
include/rocksdb/merge_operator.h
include/rocksdb/utilities/ldb_cmd.h
table/get_context.cc
tools/ldb_cmd.cc
tools/ldb_cmd_impl.h
tools/ldb_test.py
tools/ldb_tool.cc

Summary:
We add two subcommands `write_extern_sst` and `ingest_extern_sst` to ldb. This PR avoids changing existing code because we hope to cherry-pick to earlier releases to support compatibility check for external SST file ingestion.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/4205
Differential Revision: D9112711
Pulled By: riversand963
fbshipit-source-id: 7cae88380d4de86da8440230e87eca66755648e4

Add SST ingestion to ldb (#4205)

---

defs.bzl

This file appears to have been missed in the following commit:
https://github.com/facebook/rocksdb/commit/a3ab59d0304e8c199b6d5c479bd7e6b5f4933407#diff-25ca2925c669fb9025f484ff8f63d455R2
It prevents the next release version from being landed internally.

[sync fix] Add defs.bzl

---

Makefile
build_tools/build_detect_platform
java/crossbuild/docker-build-linux-centos.sh
java/rocksjni/loggerjnicallback.cc
java/src/main/java/org/rocksdb/util/Environment.java
java/src/test/java/org/rocksdb/util/EnvironmentTest.java
src.mk
util/crc32c.cc
util/crc32c_arm64.cc
util/crc32c_arm64.h

In response to https://github.com/facebook/rocksdb/issues/6188
As requested by @siying

ARM64 commits to 5.18.3 to create 5.18.4

---

HISTORY.md
db/db_impl/db_impl.cc
include/rocksdb/version.h
utilities/transactions/transaction_test.cc

Summary:
TransactionDB uses read callback to filter out un-committed data before
a snapshot. But `MultiGet()` API doesn't use that at all, which causes
returning unwanted data.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/7963
Test Plan: Added unittest to reproduce
Reviewed By: anand1976
Differential Revision: D26455851
Pulled By: jay-zhuang
fbshipit-source-id: 265276698cf9d8c4cd79e3250ef10d14375bac55

[no-review] Trigger test for 6.17.3 release

---

cache/clock_cache.cc
cache/lru_cache.cc
cache/lru_cache.h
cache/lru_cache_test.cc
cache/sharded_cache.cc
cache/sharded_cache.h
db/db_basic_test.cc
db/db_block_cache_test.cc
db/db_test_util.h
include/rocksdb/cache.h
include/rocksdb/nvm_cache.h
include/rocksdb/tiered_cache.h
utilities/simulator_cache/sim_cache.cc

Defined the abstract interface for a NVM/persistent cache in ```include/rocksdb/nvm_cache.h```, and updated ```LRUCacheOptions``` to take a ```std::shared_ptr<NvmCache>```. An item is initially inserted into the LRU cache. When it ages out and evicted from memory, its inserted into the NVM cache. On a LRU cache miss and successful lookup in NVM, the item is promoted to the in memory cache. Only support synchronous lookup currently.

[POC] Initial support for NVM cache in LRUCache

---

include/rocksdb/file_system.h

Backport of https://github.com/facebook/rocksdb/pull/9144 to the 6.26.fb branch
----
Before this fix compilation with GCC 4.8.5 20150623 (Red Hat 4.8.5-36) would fail with the following error:
```
CC       jls/db/db_impl/db_impl.o
In file included from ./env/file_system_tracer.h:8:0,
from ./file/random_access_file_reader.h:15,
from ./file/file_prefetch_buffer.h:15,
from ./table/format.h:13,
from ./table/internal_iterator.h:14,
from ./db/pinned_iterators_manager.h:12,
from ./db/range_tombstone_fragmenter.h:15,
from ./db/memtable.h:22,
from ./db/memtable_list.h:16,
from ./db/column_family.h:17,
from ./db/db_impl/db_impl.h:22,
from db/db_impl/db_impl.cc:9:
./include/rocksdb/file_system.h:108:8: error: unused parameter 'opts'
[-Werror=unused-parameter]
struct FileOptions : EnvOptions {
^ …
```

6.26.fb - Fix an error on GCC 4.8.5 where -Werror=unused-parameter fails

---

Makefile

Correct the location of zlib 1.2.11. I had to fix this to build RocksJava in 7.1.fb.

[7.1.fb] Retrieve ZLib from the archive

---

Makefile

Correct the location of zlib 1.2.11. I had to fix this to build RocksJava in 7.0.fb.

[7.0.fb] Retrieve ZLib from the archive

---

Makefile

Correct the location of zlib 1.2.11. I had to fix this to build RocksJava in 6.29.fb.

[6.29.fb] Retrieve ZLib from the archive

---

HISTORY.md
include/rocksdb/version.h
table/block_based/partitioned_filter_block.cc
table/block_based/partitioned_filter_block.h

Summary:
This patch includes following PRs:
https://github.com/facebook/rocksdb/pull/10438 : 1aab5b3 : Update passing rate_limiter_priority for a PartitionedFilterBlockReader function to FS
Test Plan:
Unit Test

Update History.md and version.h for 7.5.1

---

HISTORY.md
db/db_test2.cc
db/version_edit_handler.cc
db/version_edit_handler.h
db/version_set.cc
db/version_set.h
include/rocksdb/options.h

Summary:
The check for SST unique IDs added to best-efforts recovery (`Options::best_efforts_recovery` is true).
With best_efforts_recovery being true, RocksDB will recover to the latest point in MANIFEST such that all valid SST files included up to this point pass unique ID checks as well.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/10962
Test Plan: make check
Reviewed By: pdillinger
Differential Revision: D41378241
Pulled By: riversand963
fbshipit-source-id: a036064e2c17dec13d080a24ef2a9f85d607b16c

Make best-efforts recovery verify SST unique ID before Version construction

---

HISTORY.md
db/db_test2.cc
db/version_edit_handler.cc
db/version_edit_handler.h
db/version_set.cc
db/version_set.h
include/rocksdb/options.h

Summary:
The check for SST unique IDs added to best-efforts recovery (`Options::best_efforts_recovery` is true).
With best_efforts_recovery being true, RocksDB will recover to the latest point in MANIFEST such that all valid SST files included up to this point pass unique ID checks as well.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/10962
Test Plan: make check
Reviewed By: pdillinger
Differential Revision: D41378241
Pulled By: riversand963
fbshipit-source-id: a036064e2c17dec13d080a24ef2a9f85d607b16c

Make best-efforts recovery verify SST unique ID before Version construction (#10962)

---

HISTORY.md
db/db_impl/db_impl.cc
db/db_range_del_test.cc
include/rocksdb/options.h
table/merging_iterator.cc
table/merging_iterator.h

Summary:
Currently, `iterate_upper_bound` is not checked for range tombstone keys in MergingIterator. This may impact performance when there is a large number of range tombstones right after `iterate_upper_bound`. This PR fixes this issue by checking `iterate_upper_bound` in MergingIterator for range tombstone keys.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/10966
Test Plan:
- added unit test
- stress test: `python3 tools/db_crashtest.py whitebox --simple --verify_iterator_with_expected_state_one_in=5 --delrangepercent=5 --prefixpercent=18 --writepercent=48 --readpercen=15 --duration=36000 --range_deletion_width=100`
- ran different stress tests over sandcastle
- Falcon team ran some test traffic and saw reduced CPU usage on processing range tombstones.

[7.9] Prevent iterating over range tombstones beyond `iterate_upper_bound`

---

HISTORY.md
include/rocksdb/version.h
table/merging_iterator.cc

This should only affect iterator when
- user uses DeleteRange(), 
- An iterator from level L has a non-ok status (such non-ok status may not be caught before the bug fix in https://github.com/facebook/rocksdb/pull/11783), and
- A range tombstone covers a key from level > L and triggers a reseek sets the status_ to OK in SeekImpl()/SeekPrevImpl() e.g. https://github.com/facebook/rocksdb/blob/bd6a8340c3a2db764620e90b3ac5be173fc68a0c/table/merging_iterator.cc#L801

8.5.2 Fix a bug where iterator can return incorrect data for DeleteRange() users

---

HISTORY.md
include/rocksdb/version.h
table/compaction_merging_iterator.cc
table/merging_iterator.cc

Backport the fixes in https://github.com/facebook/rocksdb/pull/11782 and https://github.com/facebook/rocksdb/pull/11786 to 8.6 branch.

8.6.3 Include iterator status check and delete range fix.
